# ============================================================
# inventory-task1.ini — «свежий сервер» для задачи 1
# ============================================================

[fresh_servers]
fresh-server ansible_host=localhost ansible_port=2222 ansible_user=root ansible_password=root

[fresh_servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
