# ============================================================
# inventory.ini — список хостов для Ansible
# ============================================================
 
[local]
localhost ansible_connection=local ansible_user=itsme
